[font]
size = 13.0

[font.bold]
family = "JetBrains Mono"
style = "Bold"

[font.bold_italic]
family = "JetBrains Mono"
style = "Bold Italic"

[font.italic]
family = "JetBrains Mono"
style = "Italic"

[font.normal]
family = "JetBrains Mono"
style = "Regular"

[window]
title = "alacritty"
opacity = 0.5
blur = false 

[cursor]
style = "beam"

[colors.primary]
foreground = "#ffffff"
background = "#000000"
